export ALGOD_ENDPOINT="https://testnet-algorand.api.purestake.io/ps2"
export ALGOD_TOKEN="LGG679KlpG3kSNMWRpbr48XhlCUknSEC7gO0d1I5"
export INDEXER_ENDPOINT="https://testnet-algorand.api.purestake.io/idx2"
export INDEXER_TOKEN="$ALGOD_TOKEN"
export DEVELOPER_ACCOUNT_PRIVATE_KEY="chunk scout rich drip banana brick only engine awesome maid space taste weird multiply guilt skill grace chat wagon zoo grit essay swing abandon viable"
export TEST_ACCOUNT_PRIVATE_KEY="scrub slow box erosion easily violin economy sustain skin radar snake good laundry bracket popular decorate twist biology feel shuffle gallery noble limit about shaft"

export ESCROW_ADDRESS="TWQNZUE3SDL7VQZCEEDKXUGTF2VSTQ6BLJLO5JYXKGANQHARRN46BYWGZ4"
export ESCROW_LOGICSIG="AiALAQMGzIHABsuBwAYCBJCN1AXNgcAGzoHABs+BwAYyBCISQAA7MgQjEkAAAQAzABAkEjMAGCUSEDMBECQSEDMBGCEEEhAxFiEFEhAxECEGEhAxCTIDEhAxFTIDEhBCADkxGSISMQQhBw4QMRglEjEYIQQSERAxECEGEjEAMRQSEDEEIQcOEDERIQgSMREhCRIRMREhChIREBE="
export MANAGER_INDEX="13631691"
export VALIDATOR_INDEX="13631692"
export TOKEN1_INDEX="13631693"
export TOKEN2_INDEX="13631694"
export LIQUIDITY_TOKEN_INDEX="13631695"