export ALGOD_ENDPOINT="https://testnet-algorand.api.purestake.io/ps2"
export ALGOD_TOKEN="LGG679KlpG3kSNMWRpbr48XhlCUknSEC7gO0d1I5"
export INDEXER_ENDPOINT="https://testnet-algorand.api.purestake.io/idx2"
export INDEXER_TOKEN="$ALGOD_TOKEN"
export DEVELOPER_ACCOUNT_PRIVATE_KEY="circle enter hole blouse van until banana member list model protect fee unable pill between cargo model knife between high history trust coast able swing"
export TEST_ACCOUNT_PRIVATE_KEY="emerge demand wrist flame happy label place kitten ladder zoo senior suit combine angry parade dove parrot law street grain shrug admit happy abandon aisle"

export ESCROW_ADDRESS="VF35RGNY6GUFGB4LDD7CRZVJHJP4TE57XZ634SQD7AJX5MNTIT6UAATT2E"
export ESCROW_LOGICSIG="AiALAQMG67O+Bu+zvgYCBIe30QXzs74G9bO+BvuzvgYyBCISQAA7MgQjEkAAAQAzABAkEjMAGCUSEDMBECQSEDMBGCEEEhAxFiEFEhAxECEGEhAxCTIDEhAxFTIDEhBCADkxGSISMQQhBw4QMRglEjEYIQQSERAxECEGEjEAMRQSEDEEIQcOEDERIQgSMREhCRIRMREhChIREBE="
export VALIDATOR_INDEX="13616886"
export MANAGER_INDEX="13616887"
export TOKEN1_INDEX="13616888"
export TOKEN2_INDEX="13616889"
export LIQUIDITY_TOKEN_INDEX="13616890"

